In [1]:
import pandas as pd
import numpy as np

In [2]:
coworking = pd.read_csv("..\Raw data\coworking_space.csv")
marketing = pd.read_csv("..\Raw data\marketing_agency.csv")

<>:1: SyntaxWarning: "\R" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\R"? A raw string is also an option.
<>:2: SyntaxWarning: "\R" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\R"? A raw string is also an option.
<>:1: SyntaxWarning: "\R" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\R"? A raw string is also an option.
<>:2: SyntaxWarning: "\R" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\R"? A raw string is also an option.
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16284\2979639958.py:1: SyntaxWarning: "\R" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\R"? A raw string is also an option.
  coworking = pd.read_csv("..\Raw data\coworking_space.csv")
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16284\2979639958.py:2: SyntaxWarning: "\R" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\R"? A raw string is also an option.
  marketing = pd.read_csv("..\Raw data\marketing_agency.csv")

In [5]:
# Coworking file Data cleaning
coworking.shape

(563, 43)

In [8]:
coworking.head()

,place_id,name,description,is_spending_on_ads,reviews,rating,competitors,website,phone,can_claim,...,images,hours,most_popular_times,popular_times,menu,reservations,order_online_links,featured_reviews,detailed_reviews,query
0,ChIJyWO4Ydq3sw0RabTa1I4CNBE,O'Clock Coworking Space Agadir - Espace de tra...,"Situé au cœur d’Agadir, O'clock Coworking est ...",False,126,4.9,"[{'name': 'Technopark Agadir', 'link': 'https:...",http://oclockcoworking.ma/,+212 668-096709,False,...,"[{'about': 'All', 'link': 'https://lh3.ggpht.c...","[{'day': 'Monday', 'times': ['Open 24 hours']}...",Not Present,Not Present,NaN,[],"[{'link': 'https://wa.me/212751269364', 'sourc...",[{'review_id': 'ChZDSUhNMG9nS0VLLVMtOER0ajltN0...,[],coworking space in agadir
1,ChIJsZNCAPq3sw0RZ0luc4iVNYo,Coworking Space Agadir - Work Harmony Space,Work Harmony est un espace de coworking modern...,False,51,5.0,"[{'name': ""O'Clock Coworking Space Agadir - Es...",https://workharmonyspace.com/,+212 648-448743,False,...,"[{'about': 'All', 'link': 'https://lh3.ggpht.c...","[{'day': 'Monday', 'times': ['Open 24 hours']}...",Not Present,Not Present,NaN,[],[],[{'review_id': 'ChZDSUhNMG9nS0VJQ0FnSUR2Z0ppcF...,[],coworking space in agadir
2,ChIJfwom57fJsw0R06gfpYjQ9E4,Technopark Agadir,Fédérateur stratégique de l'écosystème entrepr...,False,93,4.6,"[{'name': ""O'Clock Coworking Space Agadir - Es...",https://www.technopark.ma/,NaN,False,...,"[{'about': 'All', 'link': 'https://lh3.ggpht.c...","[{'day': 'Monday', 'times': ['9\u202fAM–6\u202...",Not Present,Not Present,NaN,[],[],[{'review_id': 'ChZDSUhNMG9nS0VJQ0FnSUQyanZpVE...,[],coworking space in agadir
3,ChIJW0v7EGW3sw0RtqRMDzwAMfw,Social Innovation Space - SIS,NaN,False,14,4.7,"[{'name': ""O'Clock Coworking Space Agadir - Es...",https://www.facebook.com/ajtcd.sis/,+212 5282-29705,True,...,"[{'about': 'All', 'link': 'https://lh3.ggpht.c...","[{'day': 'Monday', 'times': ['9:30\u202fAM–12\...",Not Present,Not Present,NaN,[],[],[{'review_id': 'ChZDSUhNMG9nS0VJQ0FnSUQwc1pqNk...,[],coworking space in agadir
4,ChIJ4am5D_rJsw0R-VugqMYvslI,Y'office,📍Louez une salle de Formation ou de Réunion à ...,False,35,5.0,"[{'name': ""O'Clock Coworking Space Agadir - Es...",http://www.yoffice.ma/,+212 663-446654,False,...,"[{'about': 'All', 'link': 'https://lh3.ggpht.c...","[{'day': 'Monday', 'times': ['8:30\u202fAM–9\u...",Not Present,Not Present,NaN,[],[],[{'review_id': 'ChZDSUhNMG9nS0VJQ0FnSUNsODQyVk...,[],coworking space in agadir

In [9]:
coworking.info()

<class 'pandas.DataFrame'>
RangeIndex: 563 entries, 0 to 562
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   place_id               563 non-null    str
 1   name                   563 non-null    str
 2   description            298 non-null    str
 3   is_spending_on_ads     563 non-null    bool
 4   reviews                563 non-null    int64
 5   rating                 563 non-null    float64
 6   competitors            563 non-null    str
 7   website                263 non-null    str
 8   phone                  429 non-null    str
 9   can_claim              563 non-null    bool
 10  owner                  563 non-null    str
 11  featured_image         426 non-null    str
 12  main_category          561 non-null    str
 13  categories             561 non-null    str
 14  workday_timing         405 non-null    str
 15  is_temporarily_closed  563 non-null    bool
 16  is_permanently_closed  563 non-null    bool
 17  closed_on              563 non-null    str
 18  address                553 non-null    str
 19  review_keywords        563 non-null    str
 20  link                   563 non-null    str
 21  status                 405 non-null    str
 22  price_range            23 non-null     str
 23  reviews_per_rating     563 non-null    str
 24  featured_question      63 non-null     str
 25  reviews_link           563 non-null    str
 26  coordinates            563 non-null    str
 27  plus_code              429 non-null    str
 28  detailed_address       563 non-null    str
 29  time_zone              563 non-null    str
 30  cid                    563 non-null    uint64
 31  data_id                563 non-null    str
 32  about                  563 non-null    str
 33  images                 563 non-null    str
 34  hours                  563 non-null    str
 35  most_popular_times     563 non-null    str
 36  popular_times          563 non-null    str
 37  menu                   3 non-null      str
 38  reservations           563 non-null    str
 39  order_online_links     563 non-null    str
 40  featured_reviews       563 non-null    str
 41  detailed_reviews       563 non-null    str
 42  query                  563 non-null    str
dtypes: bool(4), float64(1), int64(1), str(36), uint64(1)
memory usage: 173.9 KB

In [10]:
coworking.isnull().sum()

place_id                   0
name                       0
description              265
is_spending_on_ads         0
reviews                    0
rating                     0
competitors                0
website                  300
phone                    134
can_claim                  0
owner                      0
featured_image           137
main_category              2
categories                 2
workday_timing           158
is_temporarily_closed      0
is_permanently_closed      0
closed_on                  0
address                   10
review_keywords            0
link                       0
status                   158
price_range              540
reviews_per_rating         0
featured_question        500
reviews_link               0
coordinates                0
plus_code                134
detailed_address           0
time_zone                  0
cid                        0
data_id                    0
about                      0
images                     0
hours                      0
most_popular_times         0
popular_times              0
menu                     560
reservations               0
order_online_links         0
featured_reviews           0
detailed_reviews           0
query                      0
dtype: int64

In [11]:
coworking.duplicated().sum()

np.int64(0)

In [12]:
coworking.columns

Index(['place_id', 'name', 'description', 'is_spending_on_ads', 'reviews',
       'rating', 'competitors', 'website', 'phone', 'can_claim', 'owner',
       'featured_image', 'main_category', 'categories', 'workday_timing',
       'is_temporarily_closed', 'is_permanently_closed', 'closed_on',
       'address', 'review_keywords', 'link', 'status', 'price_range',
       'reviews_per_rating', 'featured_question', 'reviews_link',
       'coordinates', 'plus_code', 'detailed_address', 'time_zone', 'cid',
       'data_id', 'about', 'images', 'hours', 'most_popular_times',
       'popular_times', 'menu', 'reservations', 'order_online_links',
       'featured_reviews', 'detailed_reviews', 'query'],
      dtype='str')

In [22]:
coworking["website"] = coworking["website"].fillna('Not Available')
coworking["phone"] = coworking["phone"].fillna('Not Available')

In [23]:
coworking["address"] = coworking["address"].fillna('Unknown')

In [24]:
coworking["main_category"] = coworking["main_category"].fillna('Unknown')

In [25]:
coworking["status"] = coworking["status"].fillna("Unknown")

In [38]:
coworking.isnull().sum()

place_id                   0
name                       0
is_spending_on_ads         0
reviews                    0
rating                     0
competitors                0
website                    0
phone                      0
can_claim                  0
owner                      0
main_category              0
categories                 0
workday_timing             0
is_temporarily_closed      0
is_permanently_closed      0
closed_on                  0
address                    0
review_keywords            0
link                       0
status                     0
reviews_per_rating         0
reviews_link               0
coordinates                0
detailed_address           0
time_zone                  0
cid                        0
data_id                    0
about                      0
images                     0
hours                      0
most_popular_times         0
popular_times              0
menu                     560
reservations               0
order_online_links         0
featured_reviews           0
detailed_reviews           0
query                      0
dtype: int64

In [28]:
coworking = coworking.drop(columns=["description"])
coworking = coworking.drop(columns=['featured_image'])

In [29]:
coworking['categories'] = coworking['categories'].fillna('unknown')

In [31]:
coworking = coworking.drop(columns=["plus_code"])

In [32]:
coworking["workday_timing"].head()

0    Open 24 hours
1    Open 24 hours
2        9 AM–6 PM
3    9:30 AM–12 AM
4     8:30 AM–9 PM
Name: workday_timing, dtype: str

In [35]:
coworking["workday_timing"].value_counts(dropna=False).head()

workday_timing
Not Available    158
Open 24 hours     78
9 AM–6 PM         28
9 AM–7 PM         25
9 AM–5 PM         24
Name: count, dtype: int64

In [34]:
coworking["workday_timing"] = coworking["workday_timing"].fillna("Not Available")

In [36]:
coworking["workday_timing"].value_counts().head()

workday_timing
Not Available    158
Open 24 hours     78
9 AM–6 PM         28
9 AM–7 PM         25
9 AM–5 PM         24
Name: count, dtype: int64

In [37]:
coworking[["rating","reviews","competitors"]].describe()

           rating      reviews
count  563.000000   563.000000
mean     3.614387    50.760213
std      1.946808   175.614805
min      0.000000     0.000000
25%      3.300000     1.000000
50%      4.600000     5.000000
75%      5.000000    36.500000
max      5.000000  2438.000000

In [39]:
coworking["rating"].value_counts().sort_index()

rating
0.0    118
1.0      3
1.7      1
2.3      3
2.5      2
2.8      2
3.0      7
3.1      2
3.3      6
3.4      3
3.5      1
3.6      2
3.7      6
3.8      4
3.9      7
4.0     24
4.1     15
4.2     12
4.3     16
4.4     13
4.5     14
4.6     22
4.7     23
4.8     33
4.9     45
5.0    179
Name: count, dtype: int64

In [40]:
coworking.sort_values(by="reviews", ascending= False)[["name","rating","reviews"]].head(10)

                                         name  rating  reviews
472                       Pilot Travel Center     4.1     2438
37                 Kasbah Hôtel Xaluca Arfoud     4.6     1846
475                     Sportsman's Warehouse     4.3     1233
471           Hampton Inn Richland/Tri-Cities     4.6     1140
217                                  تكنوبارك     4.1      997
245                      Bondi Coffee Kitchen     4.2      852
248  Melliber Casablanca Hotel & Appart Hotel     4.0      764
98                                    La Côte     2.5      721
289                           Atlantic Hostel     4.4      653
474                          Wilco Farm Store     4.6      549

In [41]:
coworking.sort_values(by="rating", ascending=False)[["name","rating","reviews"]]

                                                  name  rating  reviews
4                                             Y'office     5.0       35
562                                        Innocospace     5.0       20
1          Coworking Space Agadir - Work Harmony Space     5.0       51
5                                  Mao coworking space     5.0       48
542  LIK SPACE | الفضاء ليك | شبكة الرواد الشباب تيفلت     5.0        1
..                                                 ...     ...      ...
80                                         Agora Space     0.0        0
522                               Espace Taounate Info     0.0        0
521                                         M.Institut     0.0        0
517                                        Pre-history     0.0        0
9                                 IWGS coworking space     0.0        0

[563 rows x 3 columns]

In [42]:
coworking.dtypes

place_id                     str
name                         str
is_spending_on_ads          bool
reviews                    int64
rating                   float64
competitors                  str
website                      str
phone                        str
can_claim                   bool
owner                        str
main_category                str
categories                   str
workday_timing               str
is_temporarily_closed       bool
is_permanently_closed       bool
closed_on                    str
address                      str
review_keywords              str
link                         str
status                       str
reviews_per_rating           str
reviews_link                 str
coordinates                  str
detailed_address             str
time_zone                    str
cid                       uint64
data_id                      str
about                        str
images                       str
hours                        str
most_popular_times           str
popular_times                str
menu                         str
reservations                 str
order_online_links           str
featured_reviews             str
detailed_reviews             str
query                        str
dtype: object

In [46]:
# Marketing File Data Cleaning
marketing.shape

(2625, 43)

In [47]:
marketing.head()

,place_id,name,description,is_spending_on_ads,reviews,rating,competitors,website,phone,can_claim,...,images,hours,most_popular_times,popular_times,menu,reservations,order_online_links,featured_reviews,detailed_reviews,query
0,ChIJq_HKijTJsw0R0p6eiMS83zs,Kalenya - Agence de marketing digital,NaN,False,32,4.8,[{'name': 'Winu Marketing I Agence de Communic...,NaN,+212 668-789071,False,...,"[{'about': 'All', 'link': 'https://lh3.ggpht.c...","[{'day': 'Monday', 'times': ['9\u202fAM–6\u202...",Not Present,Not Present,NaN,[],"[{'link': 'https://go.kalenya.com/smc', 'sourc...",[{'review_id': 'ChZDSUhNMG9nS0VJQ0FnSUNxOFBlUk...,[],agence marketing in agadir
1,ChIJ7-FdddnFsw0RMZvs4YB7AXw,Otyss Marketing,Otyss Marketing is a premier digital marketing...,False,25,4.8,[{'name': 'Kalenya - Agence de marketing digit...,http://otyss.com/,+212 8085-53087,False,...,"[{'about': 'All', 'link': 'https://lh3.ggpht.c...","[{'day': 'Monday', 'times': ['8:30\u202fAM–1\u...",Not Present,Not Present,NaN,[],"[{'link': 'https://otyss.com/contact/', 'sourc...",[{'review_id': 'ChZDSUhNMG9nS0VJQ0FnSUN0bk9IQW...,[],agence marketing in agadir
2,ChIJTzgi3Ey2sw0R9dF0N3rv0KM,Energiedin,Agence web Maroc : création de sites et référe...,False,98,4.7,[{'name': 'Winu Marketing I Agence de Communic...,https://www.energiedin.ma/?utm_source=mybusine...,+212 5282-33354,False,...,"[{'about': 'All', 'link': 'https://lh3.ggpht.c...","[{'day': 'Monday', 'times': ['9\u202fAM–9\u202...",Not Present,Not Present,NaN,[],[{'link': 'https://www.energiedin.ma/nous-cont...,[{'review_id': 'ChZDSUhNMG9nS0VJQ0FnSURHeE9xaE...,[],agence marketing in agadir
3,ChIJLXu-hhyNvEMRhtHG0XpBFIE,Winu Marketing I Agence de Communication et Ma...,"Bienvenue chez Winu Marketing, votre partenair...",False,89,5.0,"[{'name': 'Energiedin', 'link': 'https://www.g...",https://winumaroc.com/,+212 772-044700,False,...,"[{'about': 'All', 'link': 'https://lh3.ggpht.c...","[{'day': 'Monday', 'times': ['Open 24 hours']}...",Not Present,Not Present,NaN,[],"[{'link': 'https://wa.me/+212772044700', 'sour...",[{'review_id': 'ChZDSUhNMG9nS0VJQ0FnSUNYOEs2cU...,[],agence marketing in agadir
4,ChIJ2eKqj3W3sw0RWKFbbv-mccw,ELVISUEL - Agence marketing digital agadir,Elvisuel est une agence web basée à Agadir spé...,False,7,5.0,"[{'name': 'Energiedin', 'link': 'https://www.g...",https://elvisuel.com/,+212 708-874434,False,...,"[{'about': 'All', 'link': 'https://lh3.ggpht.c...","[{'day': 'Monday', 'times': ['9\u202fAM–6\u202...",Not Present,Not Present,NaN,[],"[{'link': 'https://elvisuel.com/', 'source': '...",[{'review_id': 'ChZDSUhNMG9nS0VJQ0FnSUN5eGU3S0...,[],agence marketing in agadir

In [49]:
marketing.info()

<class 'pandas.DataFrame'>
RangeIndex: 2625 entries, 0 to 2624
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   place_id               2625 non-null   str
 1   name                   2625 non-null   str
 2   description            1728 non-null   str
 3   is_spending_on_ads     2625 non-null   bool
 4   reviews                2625 non-null   int64
 5   rating                 2625 non-null   float64
 6   competitors            2625 non-null   str
 7   website                1409 non-null   str
 8   phone                  2388 non-null   str
 9   can_claim              2625 non-null   bool
 10  owner                  2625 non-null   str
 11  featured_image         1896 non-null   str
 12  main_category          2621 non-null   str
 13  categories             2621 non-null   str
 14  workday_timing         2283 non-null   str
 15  is_temporarily_closed  2625 non-null   bool
 16  is_permanently_closed  2625 non-null   bool
 17  closed_on              2625 non-null   str
 18  address                2370 non-null   str
 19  review_keywords        2625 non-null   str
 20  link                   2625 non-null   str
 21  status                 2283 non-null   str
 22  price_range            1 non-null      str
 23  reviews_per_rating     2625 non-null   str
 24  featured_question      130 non-null    str
 25  reviews_link           2625 non-null   str
 26  coordinates            2625 non-null   str
 27  plus_code              2094 non-null   str
 28  detailed_address       2625 non-null   str
 29  time_zone              2625 non-null   str
 30  cid                    2625 non-null   uint64
 31  data_id                2625 non-null   str
 32  about                  2625 non-null   str
 33  images                 2625 non-null   str
 34  hours                  2625 non-null   str
 35  most_popular_times     2625 non-null   str
 36  popular_times          2625 non-null   str
 37  menu                   0 non-null      float64
 38  reservations           2625 non-null   str
 39  order_online_links     2625 non-null   str
 40  featured_reviews       2625 non-null   str
 41  detailed_reviews       2625 non-null   str
 42  query                  2625 non-null   str
dtypes: bool(4), float64(2), int64(1), str(35), uint64(1)
memory usage: 810.2 KB

In [69]:
marketing.isnull().sum()

place_id                    0
name                        0
is_spending_on_ads          0
reviews                     0
rating                      0
competitors                 0
website                     0
phone                       0
can_claim                   0
owner                       0
main_category               0
categories                  0
workday_timing              0
is_temporarily_closed       0
is_permanently_closed       0
closed_on                   0
address                     0
review_keywords             0
link                        0
status                      0
reviews_per_rating          0
reviews_link                0
coordinates                 0
detailed_address            0
time_zone                   0
cid                         0
data_id                     0
about                       0
images                      0
hours                       0
most_popular_times          0
popular_times               0
menu                     2625
reservations                0
order_online_links          0
featured_reviews            0
detailed_reviews            0
query                       0
dtype: int64

In [52]:
marketing = marketing.drop(columns=["featured_question"])

In [55]:
marketing.duplicated().sum()

np.int64(0)

In [56]:
marketing = marketing.drop(columns=["price_range"])

In [58]:
marketing = marketing.drop(columns=["description"])

In [59]:
marketing["website"] = marketing["website"].fillna('Not Available')

In [60]:
marketing["phone"] = marketing["phone"].fillna("Not Available")

In [62]:
marketing["address"] = marketing["address"].fillna("Unknown")

In [64]:
marketing["main_category"] = marketing["main_category"].fillna("Unknown")
marketing["categories"] = marketing["categories"].fillna("Unknown")

In [66]:
marketing = marketing.drop(columns=["plus_code"])

In [68]:
marketing["workday_timing"] = marketing["workday_timing"].fillna("Not Available")
marketing["status"] = marketing["status"].fillna("Uknown")

In [ ]:
# Analyzing the data
# Rating Summary
coworking['rating'].describe()

count    563.000000
mean       3.614387
std        1.946808
min        0.000000
25%        3.300000
50%        4.600000
75%        5.000000
max        5.000000
Name: rating, dtype: float64

In [ ]:
# Review Summary
coworking['reviews'].describe()

count     563.000000
mean       50.760213
std       175.614805
min         0.000000
25%         1.000000
50%         5.000000
75%        36.500000
max      2438.000000
Name: reviews, dtype: float64

In [ ]:
# Total Reviews in market
coworking['reviews'].sum()

np.int64(28578)

In [ ]:
# Top 10 Most Reviewed coworking space 
coworking.sort_values(by= 'reviews', ascending= False)[['name','rating','reviews']].head(10)

                                         name  rating  reviews
472                       Pilot Travel Center     4.1     2438
37                 Kasbah Hôtel Xaluca Arfoud     4.6     1846
475                     Sportsman's Warehouse     4.3     1233
471           Hampton Inn Richland/Tri-Cities     4.6     1140
217                                  تكنوبارك     4.1      997
245                      Bondi Coffee Kitchen     4.2      852
248  Melliber Casablanca Hotel & Appart Hotel     4.0      764
98                                    La Côte     2.5      721
289                           Atlantic Hostel     4.4      653
474                          Wilco Farm Store     4.6      549

In [ ]:
# Rating Distribution
coworking["rating"].value_counts().sort_index()

rating
0.0    118
1.0      3
1.7      1
2.3      3
2.5      2
2.8      2
3.0      7
3.1      2
3.3      6
3.4      3
3.5      1
3.6      2
3.7      6
3.8      4
3.9      7
4.0     24
4.1     15
4.2     12
4.3     16
4.4     13
4.5     14
4.6     22
4.7     23
4.8     33
4.9     45
5.0    179
Name: count, dtype: int64

In [15]:
coworking_clean_rating = coworking[coworking["rating"] > 0]
coworking_clean_rating["rating"].describe()

count    445.000000
mean       4.572809
std        0.636221
min        1.000000
25%        4.300000
50%        4.900000
75%        5.000000
max        5.000000
Name: rating, dtype: float64

In [ ]:
# Operating Hours Analysis
coworking["workday_timing"].value_counts().head(10)

workday_timing
Open 24 hours    78
9 AM–6 PM        28
9 AM–7 PM        25
9 AM–5 PM        24
9 AM–8 PM        18
9 AM–10 PM       11
9 AM–9 PM        10
8 AM–5 PM        10
8:30 AM–7 PM      9
8 AM–8 PM         9
Name: count, dtype: int64

In [13]:
# Main Category Analysis
coworking["main_category"].value_counts().head(15)

main_category
Coworking space               238
Business center                35
Office space rental agency     20
Cafe                           16
Coffee shop                    16
Corporate office               16
Community center               14
Government office              10
Hotel                           9
Digital printing service        6
Book store                      5
Virtual office rental           5
Learning center                 4
Restaurant                      4
Training centre                 4
Name: count, dtype: int64

In [21]:
# Competitive Column Inspection
coworking["competitors"].head(10)

0    [{'name': 'Technopark Agadir', 'link': 'https:...
1    [{'name': "O'Clock Coworking Space Agadir - Es...
2    [{'name': "O'Clock Coworking Space Agadir - Es...
3    [{'name': "O'Clock Coworking Space Agadir - Es...
4    [{'name': "O'Clock Coworking Space Agadir - Es...
5    [{'name': "O'Clock Coworking Space Agadir - Es...
6    [{'name': "O'Clock Coworking Space Agadir - Es...
7    [{'name': 'Coworking Space Agadir - Work Harmo...
8    [{'name': "Y'office", 'link': "https://www.goo...
9    [{'name': 'Coworking Space Agadir - Work Harmo...
Name: competitors, dtype: str

In [23]:
core_business = coworking[coworking["main_category"].isin(["coworking space","business center", "office space rental agency", "virtual office rental"])]

core_business.shape

(0, 44)

In [3]:
sql_coworking = coworking[
    [
        'place_id',
        'name',
        'rating',
        'reviews',
        'main_category',
        'workday_timing'
    ]
]

sql_coworking.to_csv("coworking_cleaned.csv", index= False,  encoding='utf-8-sig')

In [4]:
sql_marketing = marketing[
    [
        'place_id',
        'name',
        'rating',
        'reviews',
        'main_category',
        'workday_timing'
    ]
]

sql_marketing.to_csv("marketing_cleaned.csv", index= False,  encoding='utf-8-sig')